import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	primary: [
		'intro',
		'getting-started',
		{
			type: 'category',
			label: 'Guides',
			collapsed: false,
			link: {
				type: 'doc',
				id: 'guides/index',
			},
			items: [
				{
					type: 'category',
					label: 'Writing stories',
					collapsed: false,
					link: {
						type: 'doc',
						id: 'guides/writing-stories/index'
					},
					items: [
						'guides/writing-stories/generic',

						{
							type: 'category',
							label: 'Advanced',
							collapsed: true,
							items: [
								'guides/writing-stories/advanced/react',
								'guides/writing-stories/advanced/roact',
								'guides/writing-stories/advanced/fusion',
							]
						}
					],
				},
				'guides/migration-guide',
			]
		},
		{
			type: 'category',
			label: 'Reference',
			collapsed: false,
			items: [
				{
					type: 'link',
					label: 'API',
					href: '/api',
				},
				{
					type: 'autogenerated',
					dirName: 'reference',
				}
			]
		},
		{
			type: 'category',
			label: 'Contributing',
			link: {
				type: 'doc',
				id: 'contributing/index',
			},
			items: [
				'contributing/onboarding',
				'contributing/story-renderers',
				{
					type: 'category',
					label: 'Tech Specs',
					link: {
						type: 'doc',
						id: 'tech-specs/index',
					},
					items: [
						{
							type: 'autogenerated',
							dirName: 'tech-specs',
						},
					]
				}
			]
		},
		// {
		// 	type: 'category',
		// 	label: 'Contributing',
		// 	collapsible: true,
		// 	collapsed: true,
		// 	items: [
		// 		'contributing',
		// 		{
		// 			type: 'category',
		// 			label: 'Tech Specs',
		// 			collapsible: true,
		// 			collapsed: false,
		// 			items: [
		// 				{
		// 					type: 'autogenerated',
		// 					dirName: 'tech-specs',
		// 				},
		// 			]
		// 		}
		// 	],
		// },
	],
};

export default sidebars;
