import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	primary: [
		'intro',
		{
			type: 'category',
			label: 'Reference',
			collapsed: false,
			items: [
				{
					type: 'link',
					label: 'API',
					href: '/api',
				},
				{
					type: 'autogenerated',
					dirName: 'reference',
				}
			]
		},
		{
			type: 'category',
			label: 'Contributing',
			link: {
				type: 'doc',
				id: 'contributing/index',
			},
			items: [
				'contributing/story-renderers',
				'contributing/creating-releases',
			]
		},
	],
};

export default sidebars;
