name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install moonwave-extractor
        run: cargo install moonwave

      - name: Install dependencies
        run: npm ci
        working-directory: docs

      - name: Build docs
        run: npm run build
        working-directory: docs

      - name: Deploy docs
        if: github.event_name != 'pull_request'
        run: npm run deploy --skip-build
        working-directory: docs
        env:
          GIT_USER: github-actions[bot]
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  deploy-docs:
    if: github.event_name != 'pull_request'
    needs: [build-docs]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


